name: prosafeai github actions
run-name: ${{ github.actor }} is testing out GitHub Actions
# on: [push] # 还需要确认触发条件
on: 
  pull_request:
    types: [closed]
    branches:
      - dev
    paths:
      - "dashboard/backend/**"
      - "dashboard/web/**"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
