name: prosafeai actions
run-name: ${{ github.actor }} push
# 还需要确认触发条件
on:
  push:
    branches:
      - master
jobs:
  base-infomations:
    runs-on: ubuntu-latest
    steps:
      - name: Basic infomations
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3
  
      - name: test ssh
        # uses: appleboy/ssh-action@master
        # uses: ./.github/actions/prosafeai-ssh
        uses: sunchangkai/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            ls
